version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_nodejs
    environment:
      - RABBITMQ_DEFAULT_USER=user 
      - RABBITMQ_DEFAULT_PASS=password
networks:
  rabbitmq_nodejs:
    driver: bridge